import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {client} from '../lib/client'
import { Composition, Slot } from '@uniformdev/canvas-react';

export default function Home({ composition }) {
  console.log({composition})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Composition data={composition} resolveRenderer={() => {
        const DefaultComponent = ({heading, subheading, link, linkText}) => {
          return (
            <>
              <h1>{heading}</h1>
              <h2>{subheading}</h2>
            </>
          )
        }
      }}>
        <Slot name="hero" />
      </Composition>
      <code>{JSON.stringify(composition, null, 2)}</code>

      </main >

    </div >
  )
}

export async function getStaticProps() {
  const { composition } = await client.getCompositionBySlug({
    slug: '/',
  });
  return {
    props: {
      composition,
    },
  };
}